Kategoriler
acesur74101/LMS pull request #12
Opened 2023-07-01 12:15 UTC by Nusret-Karakus

kategori kısmı bitti

2023-07-01 13:15 UTC, acesur7410 requested changes
d flex yerine 
üst dive row
alt dive col ve ekran büyüklüklerini dikkate alarak col-md col-sm tarzı class isimleri verilmelidir.

2023-07-01 13:19 UTC, acesur7410 requested changes

2023-07-01 13:19 UTC, acesur7410 commented on kategori.html
> +                <div class="container d-flex my-0 mt-3 mb-3">
d-flex kullanılmamalı.

2023-07-01 13:19 UTC, acesur7410 commented on kategori.html
> +                    <div class="cards ms-3">
her karta ms-3 yerine 
mx classı kullanılmalı.

2023-07-01 13:19 UTC, acesur7410 commented on kategori.html
> +                    <div class="cards ms-3">
ayrıca 
c-md-2 col-sm-6 col-12 gibi classları deneyiniz.

2023-07-01 13:21 UTC, acesur74101 requested changes
düzeltme

2023-07-04 11:15 UTC, acesur74101 commented
tamamdır

2023-07-04 11:15 UTC, acesur74101 commented
tamamdır

2023-07-04 11:15 UTC, merged